### ISSUE TITLE
ingredients don’t show up in search 

### ISSUE THREAD

**Issue by arndt-s** [washeuteessen/washeuteessen-api#2]
It’s not possible to search for ingredients

**Comment by lena-kuhn** [comment]
@arndt-s 
Hab vorhin nach "Wasser" gesucht und hab Ergebnisse bekommen, wo es nicht im Titel steht, sondern in der Zutatenliste. Vlt. funktionierts doch? Oder nur in bestimmten Fällen nicht?
https://www.chefkoch.de/rezepte/1611411268351373/Nudelteig-fuer-perfekte-Pasta.html

**Comment by arndt-s** [comment]
ja, tauchen wieder auf :)
